#!/bin/sh
set -e

BUILD_DIR=$1
CACHE_DIR=$2
ENV_DIR=$3

echo "Installing dependencies..."
apt-get update
apt-get install -y build-essential curl git file pkg-config swig \
    libcairo2-dev libnetpbm10-dev netpbm libpng-dev libjpeg-dev \
    zlib1g-dev libbz2-dev libcfitsio-dev wcslib-dev \
    python3 python3-pip python3-dev \
    python3-numpy python3-scipy python3-pil
pip install fitsio

echo "Downloading Astrometry.net..."
wget http://astrometry.net/downloads/astrometry.net-latest.tar.gz
tar xvzf astrometry.net-latest.tar.gz
cd astrometry.net-*

echo "Building Astrometry.net..."
make
make py
make extra
make install INSTALL_DIR=$BUILD_DIR/astrometry

echo "Astrometry.net installed."
